# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-07 17:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='actor_movie',
            new_name='movie_genre',
        ),
    ]
