# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-16 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20180907_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='is_favourite',
            field=models.BooleanField(default=False),
        ),
    ]
