# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-19 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_songs_is_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songs',
            name='is_favourite',
        ),
        migrations.AlterField(
            model_name='movies',
            name='movie_poster',
            field=models.FileField(upload_to=''),
        ),
    ]
